services:
  - type: web
    name: inventory-api-hv03
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db-hv03
          property: connectionString
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: INITIAL_SUPER_ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRATION
        value: "900000"
      - key: JWT_REFRESH_TOKEN_EXPIRATION
        value: "604800000"
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://inventory-web-hv03.onrender.com
      - key: SPRING_MAIL_HOST
        sync: false
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false

databases:
  - name: inventory-db-hv03
    plan: free
    region: singapore
